// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH0cUDcq7523APpyHOlgB3-kkwgFollf0',
    appId: '1:504027153680:web:bf058cb53d9ade4b655195',
    messagingSenderId: '504027153680',
    projectId: 'health-factory-56e91',
    authDomain: 'health-factory-56e91.firebaseapp.com',
    storageBucket: 'health-factory-56e91.appspot.com',
    measurementId: 'G-F2W6F5FXFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVYS0By2sjxvtwyIDcvUVmhuDIKPtm-ic',
    appId: '1:504027153680:android:493830335adb2026655195',
    messagingSenderId: '504027153680',
    projectId: 'health-factory-56e91',
    storageBucket: 'health-factory-56e91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATVoadC92lKObdDagZPvB4iTbYCgCRGbI',
    appId: '1:504027153680:ios:652b12ddeff9864a655195',
    messagingSenderId: '504027153680',
    projectId: 'health-factory-56e91',
    storageBucket: 'health-factory-56e91.appspot.com',
    iosClientId: '504027153680-aqdpnhlu93vgbogj0trmevcnkbfsnd54.apps.googleusercontent.com',
    iosBundleId: 'design.specter.hf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATVoadC92lKObdDagZPvB4iTbYCgCRGbI',
    appId: '1:504027153680:ios:652b12ddeff9864a655195',
    messagingSenderId: '504027153680',
    projectId: 'health-factory-56e91',
    storageBucket: 'health-factory-56e91.appspot.com',
    iosClientId: '504027153680-aqdpnhlu93vgbogj0trmevcnkbfsnd54.apps.googleusercontent.com',
    iosBundleId: 'design.specter.hf',
  );
}
